[window]
padding = { x = 10, y = 10 }
decorations = "None"
opacity = 0.9
blur = true

[font]
normal = { family = "CascadiaCode", style = "Regular" }
size = 15

[cursor]
style = { shape = "Underline", blinking = "On" }

[mouse]
hide_when_typing = true

# (tokyo night https://github.com/zatchheems/tokyo-night-alacritty-theme/blob/main/tokyo-night.toml)
[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"
